{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Login Succeeded\n",
      "Sending build context to Docker daemon   42.5kB\n",
      "Step 1/16 : FROM continuumio/anaconda3:4.4.0\n",
      " ---> 795ad88c47ff\n",
      "Step 2/16 : RUN conda install -c anaconda setuptools\n",
      " ---> Using cache\n",
      " ---> 7646ff61d3af\n",
      "Step 3/16 : RUN apt-get -y update && apt-get install -y --no-install-recommends          libgl1-mesa-glx          wget          nginx          ca-certificates     && rm -rf /var/lib/apt/lists/*\n",
      " ---> Using cache\n",
      " ---> 420cd5bb794e\n",
      "Step 4/16 : RUN pip install --upgrade pip &&     pip install janome==0.3.10 &&     pip install tensorflow==1.14.0 --user &&     pip install ml_metrics==0.1.4 &&     pip install --upgrade scipy==1.1.0 &&     pip install flask &&     pip install -U gevent==1.4.0 --ignore-installed &&     pip install gunicorn\n",
      " ---> Using cache\n",
      " ---> 23a5ffac18cd\n",
      "Step 5/16 : RUN python -m nltk.downloader book\n",
      " ---> Using cache\n",
      " ---> 4db5f1677ff0\n",
      "Step 6/16 : ENV PYTHONUNBUFFERED=TRUE\n",
      " ---> Using cache\n",
      " ---> 3171e306868d\n",
      "Step 7/16 : ENV PYTHONDONTWRITEBYTECODE=TRUE\n",
      " ---> Using cache\n",
      " ---> 02c9f22bf71c\n",
      "Step 8/16 : ENV PATH=\"/opt/program:${PATH}\"\n",
      " ---> Using cache\n",
      " ---> 35903b506adf\n",
      "Step 9/16 : WORKDIR /opt/program\n",
      " ---> Using cache\n",
      " ---> 2f020c0d6a96\n",
      "Step 10/16 : RUN git clone https://github.com/mack-the-psych/plimac3.git\n",
      " ---> Using cache\n",
      " ---> f2f005ee993f\n",
      "Step 11/16 : RUN git clone https://github.com/mack-the-psych/vdok3.git\n",
      " ---> Using cache\n",
      " ---> 32bc180c27d0\n",
      "Step 12/16 : RUN echo \"/opt/program/plimac3/Lib\" > /opt/conda/lib/python3.6/site-packages/plimac-custom.pth\n",
      " ---> Using cache\n",
      " ---> d258e4901b5d\n",
      "Step 13/16 : RUN echo \"/opt/program/plimac3/Tools\" >> /opt/conda/lib/python3.6/site-packages/plimac-custom.pth\n",
      " ---> Using cache\n",
      " ---> 7d227eaa0195\n",
      "Step 14/16 : RUN echo \"/opt/program/vdok3/train\" >> /opt/conda/lib/python3.6/site-packages/plimac-custom.pth\n",
      " ---> Using cache\n",
      " ---> b72208cf5dcc\n",
      "Step 15/16 : COPY vdok3_sage /opt/program\n",
      " ---> a975b435d97b\n",
      "Step 16/16 : WORKDIR /opt/program\n",
      " ---> Running in 728349e216b9\n",
      "Removing intermediate container 728349e216b9\n",
      " ---> 88631ef855b8\n",
      "Successfully built 88631ef855b8\n",
      "Successfully tagged sagemaker-vdok3-memn2n:latest\n",
      "The push refers to repository [208274468343.dkr.ecr.ap-northeast-1.amazonaws.com/sagemaker-vdok3-memn2n]\n",
      "05f8b7c169e8: Preparing\n",
      "82a6c48975b5: Preparing\n",
      "90d7db08b1bf: Preparing\n",
      "8d1935f319d8: Preparing\n",
      "e0c6295731c5: Preparing\n",
      "ea9ca074c3de: Preparing\n",
      "e2a366055103: Preparing\n",
      "4fec35950a39: Preparing\n",
      "c03e6d7086ca: Preparing\n",
      "151c20a06cb8: Preparing\n",
      "3442cb97a69d: Preparing\n",
      "ca173dc10e31: Preparing\n",
      "54e10c08a841: Preparing\n",
      "1f09b1beaa90: Preparing\n",
      "9e63c5bce458: Preparing\n",
      "ea9ca074c3de: Waiting\n",
      "e2a366055103: Waiting\n",
      "4fec35950a39: Waiting\n",
      "c03e6d7086ca: Waiting\n",
      "151c20a06cb8: Waiting\n",
      "3442cb97a69d: Waiting\n",
      "ca173dc10e31: Waiting\n",
      "54e10c08a841: Waiting\n",
      "1f09b1beaa90: Waiting\n",
      "9e63c5bce458: Waiting\n",
      "82a6c48975b5: Layer already exists\n",
      "8d1935f319d8: Layer already exists\n",
      "90d7db08b1bf: Layer already exists\n",
      "e0c6295731c5: Layer already exists\n",
      "ea9ca074c3de: Layer already exists\n",
      "e2a366055103: Layer already exists\n",
      "4fec35950a39: Layer already exists\n",
      "c03e6d7086ca: Layer already exists\n",
      "3442cb97a69d: Layer already exists\n",
      "ca173dc10e31: Layer already exists\n",
      "151c20a06cb8: Layer already exists\n",
      "54e10c08a841: Layer already exists\n",
      "1f09b1beaa90: Layer already exists\n",
      "9e63c5bce458: Layer already exists\n",
      "05f8b7c169e8: Pushed\n",
      "latest: digest: sha256:b690bf0bbb344d9c363efbef22ca448eb8cd72c3c6f98b9f459e5b5b5c357636 size: 3473\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING! Using --password via the CLI is insecure. Use --password-stdin.\n",
      "WARNING! Your password will be stored unencrypted in /home/ec2-user/.docker/config.json.\n",
      "Configure a credential helper to remove this warning. See\n",
      "https://docs.docker.com/engine/reference/commandline/login/#credentials-store\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 8.84 ms, sys: 154 Âµs, total: 8.99 ms\n",
      "Wall time: 8 s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "%%sh\n",
    "\n",
    "# The name of our algorithm\n",
    "# Makoto.Sano@Mack-the-Psych.com\n",
    "algorithm_name=sagemaker-vdok3-memn2n\n",
    "\n",
    "cd container\n",
    "\n",
    "chmod +x vdok3_sage/train\n",
    "chmod +x vdok3_sage/serve\n",
    "\n",
    "account=$(aws sts get-caller-identity --query Account --output text)\n",
    "\n",
    "# Get the region defined in the current configuration (default to us-west-2 if none defined)\n",
    "region=$(aws configure get region)\n",
    "region=${region:-us-west-2}\n",
    "\n",
    "fullname=\"${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest\"\n",
    "\n",
    "# If the repository doesn't exist in ECR, create it.\n",
    "aws ecr describe-repositories --repository-names \"${algorithm_name}\" > /dev/null 2>&1\n",
    "\n",
    "if [ $? -ne 0 ]\n",
    "then\n",
    "    aws ecr create-repository --repository-name \"${algorithm_name}\" > /dev/null\n",
    "fi\n",
    "\n",
    "# Get the login command from ECR and execute it directly\n",
    "$(aws ecr get-login --region ${region} --no-include-email)\n",
    "\n",
    "# Build the docker image locally with the image name and then push it to ECR\n",
    "# with the full name.\n",
    "\n",
    "docker build  -t ${algorithm_name} .\n",
    "docker tag ${algorithm_name} ${fullname}\n",
    "\n",
    "docker push ${fullname}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# S3 prefix\n",
    "# Makoto.Sano@Mack-the-Psych.com\n",
    "prefix = 'vdok3_memn2n_trial'\n",
    "\n",
    "# Define IAM role\n",
    "import boto3\n",
    "import re\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sagemaker import get_execution_role\n",
    "\n",
    "role = get_execution_role()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker as sage\n",
    "from time import gmtime, strftime\n",
    "\n",
    "sess = sage.Session()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "WORK_DIRECTORY = 'data'\n",
    "\n",
    "data_location = sess.upload_data(WORK_DIRECTORY, key_prefix=prefix)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Parameter image_name will be renamed to image_uri in SageMaker Python SDK v2.\n",
      "'s3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2020-09-13 09:01:47 Starting - Starting the training job...\n",
      "2020-09-13 09:01:49 Starting - Launching requested ML instances......\n",
      "2020-09-13 09:03:05 Starting - Preparing the instances for training...\n",
      "2020-09-13 09:03:46 Downloading - Downloading input data...\n",
      "2020-09-13 09:03:52 Training - Downloading the training image........\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\u001b[0m\n",
      "\u001b[34m/root/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:26: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.\n",
      "\u001b[0m\n",
      "\u001b[34mStarting the training.\u001b[0m\n",
      "\u001b[34mBuilding model...\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:206: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:207: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:\u001b[0m\n",
      "\u001b[34mThe TensorFlow contrib module will not be included in TensorFlow 2.0.\u001b[0m\n",
      "\u001b[34mFor more information, please see:\n",
      "  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md\n",
      "  * https://github.com/tensorflow/addons\n",
      "  * https://github.com/tensorflow/io (for I/O related ops)\u001b[0m\n",
      "\u001b[34mIf you depend on functionality not listed there, please file an issue.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:148: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mThis class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:155: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:155: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /root/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mCall initializer instance with the dtype argument instead of passing it to the constructor\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /root/.local/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py:738: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mCall initializer instance with the dtype argument instead of passing it to the constructor\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\n",
      "2020-09-13 09:05:24 Training - Training image download completed. Training in progress.\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:Entity <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BasicLSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f18395a36d8>>: AssertionError: Bad argument number for Name: 3, expecting 4\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:219: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:180: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /root/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mUse tf.where in 2.0, which has the same broadcast rule as np.where\u001b[0m\n",
      "\u001b[34mTraining model...\u001b[0m\n",
      "\u001b[34m2020-09-13 09:05:39.376171: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\u001b[0m\n",
      "\u001b[34m2020-09-13 09:05:39.408817: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900100000 Hz\u001b[0m\n",
      "\u001b[34m2020-09-13 09:05:39.409312: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a80ab0 executing computations on platform Host. Devices:\u001b[0m\n",
      "\u001b[34m2020-09-13 09:05:39.409335: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:234: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:235: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.\n",
      "\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /opt/program/vdok3/train/tf_memn_classify.py:236: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.\n",
      "\u001b[0m\n",
      "\u001b[34m2020-09-13 09:05:39.900122: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.\u001b[0m\n",
      "\u001b[34mepoch: 0  validation loss: 0.48722908  validation accuracy: 0.86399615\u001b[0m\n",
      "\u001b[34mepoch: 1  validation loss: 0.4365284  validation accuracy: 0.86399615\u001b[0m\n",
      "\u001b[34mepoch: 2  validation loss: 0.3057394  validation accuracy: 0.86423606\u001b[0m\n",
      "\u001b[34mepoch: 3  validation loss: 0.2401758  validation accuracy: 0.887503\u001b[0m\n",
      "\u001b[34mWARNING:tensorflow:From /root/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\u001b[0m\n",
      "\u001b[34mInstructions for updating:\u001b[0m\n",
      "\u001b[34mUse standard file APIs to delete files with this prefix.\u001b[0m\n",
      "\u001b[34mepoch: 4  validation loss: 0.21118473  validation accuracy: 0.9054929\u001b[0m\n",
      "\u001b[34mepoch: 5  validation loss: 0.18714175  validation accuracy: 0.9218038\u001b[0m\n",
      "\u001b[34mepoch: 6  validation loss: 0.16716883  validation accuracy: 0.9287599\u001b[0m\n",
      "\u001b[34mepoch: 7  validation loss: 0.14931758  validation accuracy: 0.9323579\u001b[0m\n",
      "\u001b[34mepoch: 8  validation loss: 0.1353764  validation accuracy: 0.9371552\u001b[0m\n",
      "\u001b[34mepoch: 9  validation loss: 0.12261346  validation accuracy: 0.9412329\u001b[0m\n",
      "\u001b[34mepoch: 10  validation loss: 0.10843149  validation accuracy: 0.951787\u001b[0m\n",
      "\u001b[34mepoch: 11  validation loss: 0.09642665  validation accuracy: 0.9633005\u001b[0m\n",
      "\u001b[34mepoch: 12  validation loss: 0.09089742  validation accuracy: 0.96545935\u001b[0m\n",
      "\u001b[34mepoch: 13  validation loss: 0.0771447  validation accuracy: 0.97169584\u001b[0m\n",
      "\u001b[34mepoch: 14  validation loss: 0.066607  validation accuracy: 0.97505397\u001b[0m\n",
      "\u001b[34mepoch: 15  validation loss: 0.05522975  validation accuracy: 0.9829695\u001b[0m\n",
      "\u001b[34mepoch: 16  validation loss: 0.051875733  validation accuracy: 0.98632765\u001b[0m\n",
      "\u001b[34mepoch: 17  validation loss: 0.04736033  validation accuracy: 0.98320943\u001b[0m\n",
      "\u001b[34mepoch: 18  validation loss: 0.038193095  validation accuracy: 0.989206\u001b[0m\n",
      "\u001b[34mepoch: 19  validation loss: 0.040897377  validation accuracy: 0.98584795\u001b[0m\n",
      "\u001b[34mRecall                      0.9858\u001b[0m\n",
      "\u001b[34mPrecision                   0.9857\u001b[0m\n",
      "\u001b[34mF1                          0.9857\u001b[0m\n",
      "\u001b[34mKappa                       0.9413\u001b[0m\n",
      "\u001b[34mQuadratic Weighted Kappa    0.9607\u001b[0m\n",
      "\u001b[34mdtype: float64\u001b[0m\n",
      "\u001b[34mConfusion Matrix:\n",
      "      0    1    2\u001b[0m\n",
      "\u001b[34m0  3594    7    1\u001b[0m\n",
      "\u001b[34m1    14  337   11\u001b[0m\n",
      "\u001b[34m2     6   20  179\u001b[0m\n",
      "\u001b[34mModel saved to:  /opt/ml/model/vdok3_memn2n.ckpt\u001b[0m\n",
      "\u001b[34mTraining complete.\u001b[0m\n",
      "\n",
      "2020-09-13 09:06:26 Uploading - Uploading generated training model\n",
      "2020-09-13 09:06:26 Completed - Training job completed\n",
      "Training seconds: 160\n",
      "Billable seconds: 160\n"
     ]
    }
   ],
   "source": [
    "account = sess.boto_session.client('sts').get_caller_identity()['Account']\n",
    "region = sess.boto_session.region_name\n",
    "\n",
    "# Makoto.Sano@Mack-the-Psych.com\n",
    "image = '{}.dkr.ecr.{}.amazonaws.com/sagemaker-vdok3-memn2n:latest'.format(account, region)\n",
    "vdok3memn2n = sage.estimator.Estimator(image,\n",
    "                       role, 1, 'ml.c4.2xlarge',\n",
    "                       output_path=\"s3://{}/output\".format(sess.default_bucket()),\n",
    "                       sagemaker_session=sess)\n",
    "vdok3memn2n.fit(data_location)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Parameter image will be renamed to image_uri in SageMaker Python SDK v2.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-----------------!"
     ]
    }
   ],
   "source": [
    "from sagemaker.predictor import csv_serializer\n",
    "predictor = vdok3memn2n.deploy(1, 'ml.m4.xlarge', serializer=csv_serializer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Score_Class\n",
      "1\n",
      "1\n",
      "2\n",
      "0\n",
      "\n"
     ]
    }
   ],
   "source": [
    "df_in = pd.read_csv('data/Head4-Serialized-Def-ELVA.PILOT.POST-TEST.csv')\n",
    "np_in = np.vstack((np.array(df_in.columns), df_in.to_numpy()))\n",
    "print(predictor.predict(np_in).decode('utf-8'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "sess.delete_endpoint(predictor.endpoint)"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "transform_output_folder = \"batch-transform-output\"\n",
    "output_path=\"s3://{}/{}\".format(sess.default_bucket(), transform_output_folder)\n",
    "\n",
    "transformer = vdok3memn2n.transformer(instance_count=1,\n",
    "                               instance_type='ml.m4.xlarge',\n",
    "                               output_path=output_path,\n",
    "                               assemble_with='Line',\n",
    "                               accept='text/csv')"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "transformer.transform(data_location + '/Serialized-Def-ELVA.PILOT.PRE-TEST.csv', content_type='text/csv', split_type='Line')\n",
    "transformer.wait()"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "s3_client = sess.boto_session.client('s3')\n",
    "s3_client.download_file(sess.default_bucket(), \"{}/Serialized-Def-ELVA.PILOT.PRE-TEST.csv.out\".format(transform_output_folder), '/tmp/Serialized-Def-ELVA.PILOT.PRE-TEST.csv.out')\n",
    "with open('/tmp/Serialized-Def-ELVA.PILOT.PRE-TEST.csv.out') as f:\n",
    "    results = f.readlines()   \n",
    "print(\"Transform results: \\n{}\".format(''.join(results)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
